Changed fetchers to use ORACLE_HOME from args

diff --git a/fetch/dbmounted b/fetch/dbmounted
--- a/fetch/dbmounted
+++ b/fetch/dbmounted
@@ -16,9 +16,14 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 SID=$1
+HOME=$2
 
 if [ -z "$SID" ]; then
   echo "Missing SID parameter"
+  exit 1
+fi
+if [ -z "$HOME" ]; then
+  echo "Missing ORACLE_HOME parameter"
   exit 1
 fi
 
@@ -27,6 +32,7 @@ ERCOLE_HOME="$(dirname "$ERCOLE_HOME")"
 
 export ORAENV_ASK=NO 
 export ORACLE_SID=$SID
-. oraenv 1>/dev/null
+export ORACLE_HOME=$HOME
+export PATH=$HOME/bin:$PATH
 
 sqlplus -S "/ AS SYSDBA" < ${ERCOLE_HOME}/sql/dbmounted.sql
diff --git a/fetch/feature b/fetch/feature
--- a/fetch/feature
+++ b/fetch/feature
@@ -29,12 +29,20 @@ if [ -z "$DBV" ]; then
   exit 1
 fi
 
+HOME=$3
+
+if [ -z "$HOME" ]; then
+  echo "Missing ORACLE_HOME parameter"
+  exit 1
+fi
+
 ERCOLE_HOME=$(dirname "$0")
 ERCOLE_HOME="$(dirname "$ERCOLE_HOME")"
 
 export ORAENV_ASK=NO 
 export ORACLE_SID=$SID
-. oraenv 1>/dev/null
+export ORACLE_HOME=$HOME
+export PATH=$HOME/bin:$PATH
 
 if [ $DBV == "11" ] ||  [ $DBV == "12" ]; then
   sqlplus -S "/ AS SYSDBA" < ${ERCOLE_HOME}/sql/feature.sql
